# Generated by Django 5.0.6 on 2024-06-06 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Musician', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musician',
            name='instrument_type',
        ),
    ]
