# Generated by Django 5.0.6 on 2024-06-06 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Musician', '0004_remove_musician_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musician',
            old_name='phonenumber_field',
            new_name='phone_number',
        ),
    ]
